import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Blog | Next App',
  description: 'Generated by create next app',
}
const Privacy = () => {
  return <div>
    <p>
      Collection of information
      When submitting an application on the Tri Double U web studio website, clients provide the following information:
      - Name.
      — Contact email (required).
      The web studio administration also receives data about the IP address of visitors, as well as browser type, time spent on the site and other similar information. The collection is carried out using statistics services.

      Use of information
      All information received is used by the administration of the Tri Double U web studio solely for the purpose of communicating with the client. The Tri Double U web studio has the right to send information messages (newsletters) to the client if he has subscribed to them.

      Protection of personal information
      Web studio "Three Double U" undertakes not to disclose information received from clients. It is stored in a database on the local computer of the web studio administration. Access to the computer is securely protected by a password, which is available only to the site administrator.

      Providing data to third parties
      The information received cannot be transferred to third parties, except in the following cases:
      — To fulfill obligations to the client - only with his permission.
      — Subject to reasonable and applicable legal requirements.

      Contacts
      For any questions, you can contact the site administration.
      — Phone: +998910012565.
      — E-mail: 777aaauz@gmail.com.

      This version of the privacy policy was published on 15.02.24.
    </p>
  </div>
}

export default Privacy