import { Metadata } from 'next';
import { unstable_setRequestLocale } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

function Blog({ params: { locale } }: Readonly<{
  params: { locale: string }
}>) {
  unstable_setRequestLocale(locale)
  return (
    <div>
      <h1>Извините за неудобство. Мы работаем над обновлением этой страницы</h1>
    </div>
  );
}

export default Blog;