import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

function Blog() {
  return (
    <div>
      <h1>Blog</h1>
    </div>
  );
}

export default Blog;