import type { Metadata } from "next";
import Head from "next/head";
import TheHeader from '@/components/TheHeader/TheHeader';
import TheFooter from '@/components/TheFooter/TheFooter';
import "./globals.css";
import { unstable_setRequestLocale } from 'next-intl/server';

const locales = ['en', 'uz', 'ru']

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }))
}

export const metadata: Metadata = {
  title: "NutriGrow",
  description: "Generated by create next app",
  icons: {
    icon: [
      '../../../public/favicon/favicon.ico?=v1',
    ],
    apple: [
      '../../../public/favicon/apple-touch-icon.png?=v4',
    ],
    shortcut: [
      '../../../public/favicon/apple-touch-icon.png'
    ]
  },
  manifest: '../../../public/favicon/site.webmanifest'
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  unstable_setRequestLocale(locale)
  return (
    <html lang={locale}>
      <body>
        <TheHeader params={locale} />
        <main>
          <div className="container">
            {children}
          </div>
        </main>
        <TheFooter />
      </body>
    </html>
  );
}