import type { Metadata } from "next";
import Head from "next/head";
import { Inter, Open_Sans, DM_Sans, Lato } from "next/font/google";
import TheHeader from '@/components/TheHeader/TheHeader';
import TheFooter from '@/components/TheFooter/TheFooter';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NutriGrow",
  description: "Generated by create next app",
  icons: {
    icon: [
      '../../../public/favicon/favicon.ico?=v1',
    ],
    apple: [
      '../../../public/favicon/apple-touch-icon.png?=v4',
    ],
    shortcut: [
      '../../../public/favicon/apple-touch-icon.png'
    ]
  },
  manifest: '../../../public/favicon/site.webmanifest'
};

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body>
        <TheHeader />
        <main>
          <div className="container">
            {children}
          </div>
        </main>
        <TheFooter />
      </body>
    </html>
  );
}
